### ISSUE TITLE
tpa

### ISSUE THREAD

**Issue by Trxgically** [pmessentials/PMEssentials#1]
Perhaps you add /tpa please?

**Comment by AndreasHGK** [comment]
It is planned. I'm still working on a ton of commands

**Comment by Flucid** [comment]
Thanks, I’m looking to switch from EssentialsPE to this because EssentialsPE randomly crashes the server.

**Comment by AndreasHGK** [comment]
working as fast as possible

**Comment by Flucid** [comment]
Would you like some help? If so, add me to the collaboration list I’ll defined help.

**Comment by AndreasHGK** [comment]
You can fork the repository and then when you have a new feature you can open a pull request. Then i can decide wether to add it or not

**Comment by AndreasHGK** [comment]
anyway, this is not really a good way of comunicating. Contact me via discord instead. my discord: **AndreasHGK#0265**
