### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kauso8507** [pmessentials/PMEssentials#10]
/vanish and /ping don´t work pls fix :)

**Comment by Kauso8507** [comment]
okay sry, my mistake. My plugins are to blame.

**Comment by AndreasHGK** [comment]
I can’t do anything with this. Please give me more information like the error in the console, your pmmp version etc. You can use the bug template to see what info to give

**Comment by AndreasHGK** [comment]
Oh ok
