### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ChampOfGamesYT** [pmessentials/PMEssentials#11]
/afk
 /delhome
 /delwarp
 /home
 /server
 /sethome
 /setspawn
 /setwarp
 /spawn
 /tp (custom)
 /tpa
 /tpaccept
 /tpahere
 /tpdeny
 /tphere
 /tpo
 /tpohere
 /warp

**Comment by AndreasHGK** [comment]
i will work on these commands. Please do not suggest duplicates. Check other issues and the commands readme.md

**Comment by ChampOfGamesYT** [comment]
Oh okay sry
