### ISSUE TITLE
Add idea

### ISSUE THREAD

**Issue by Karanztez** [pmessentials/PMEssentials#15]
/pvp on
/pvp off

**Comment by AndreasHGK** [comment]
what would make this different from just turning on/off pvp in settings?

**Comment by Karanztez** [comment]
Players can choose to pvp or not, pvp by themselves.

**Comment by Karanztez** [comment]
This order, if possible, please set the op to allow.

**Comment by AndreasHGK** [comment]
Sorry, but I won’t add this feature as i feel like it is not general enough and there will be people that don’t want this. Could you imagine people turning off their pvp individually on a kitpvp server?
