### ISSUE TITLE
/tphere does not function [BUG]

### ISSUE THREAD

**Issue by xXRyzen** [pmessentials/PMEssentials#16]
**Describe the bug**
/tphere not recognized as a command

**Versions:**
 - Pocketmine version: PocketMine-MP 3.6.0 v1.9.0 (Protocol 332)
 - Plugin version: Latest
 - Minecraft version: Win10

**Error:**
N/A

**Comment by AndreasHGK** [comment]
This is because the command is not yet implemented. I will implement in though

**Comment by xXRyzen** [comment]
Thanks!
