### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mikeygio10** [pmessentials/PMEssentials#21]
**Describe the bug**
Don’t work says I turned server error when try to join
**To Reproduce**

**Screenshots**
If applicable, add screenshots to help explain your problem. (optional)

**Versions:**
 - Pocketmine version:  1.10
 - Plugin version:  build 47
 - Minecraft version: (version of your client eg.: pe, win10, xbox)

**Error:**
Paste the error from the console here
Down below

**Comment by mikeygio10** [comment]
19.04 01:58:31 [Server] Server thread/CRITICAL Error: "Call to a member function setLastPos() on null" (EXCEPTION) in "plugins/PMEssentials_dev-46.phar/src/pmessentials/PMEssentials/listener/BackListener" at line 17
19.04 01:58:31 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): pmessentials\PMEssentials\listener\BackListener->onTeleport(pocketmine\event\entity\EntityTeleportEvent object)
19.04 01:58:31 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(pmessentials\PMEssentials\listener\BackListener object, pocketmine\event\entity\EntityTeleportEvent object)
19.04 01:58:31 [Server] Server thread/DEBUG #2 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\entity\EntityTeleportEvent object)
19.04 01:58:31 [Server] Server thread/DEBUG #3 src/pocketmine/entity/Entity(1948): pocketmine\event\Event->call()
19.04 01:58:31 [Server] Server thread/DEBUG #4 src/pocketmine/Player(3755): pocketmine\entity\Entity->teleport(pocketmine\level\Position object, NULL , NULL )
19.04 01:58:31 [Server] Server thread/DEBUG #5 plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader(16): pocketmine\Player->teleport(pocketmine\level\Position object)
19.04 01:58:31 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/MethodEventExecutor(38): philipshilling\alwaysspawn\Loader->onPlayerLogin(pocketmine\event\player\PlayerLoginEvent object)
19.04 01:58:31 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(philipshilling\alwaysspawn\Loader object, pocketmine\event\player\PlayerLoginEvent object)
19.04 01:58:31 [Server] Server thread/DEBUG #8 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerLoginEvent object)
19.04 01:58:31 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2108): pocketmine\event\Event->call()
19.04 01:58:31 [Server] Server thread/DEBUG #10 src/pocketmine/Player(2091): pocketmine\Player->completeLoginSequence()
19.04 01:58:31 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(125): pocketmine\Player->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
19.04 01:58:31 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(62): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
19.04 01:58:31 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
19.04 01:58:31 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
19.04 01:58:31 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
19.04 01:58:31 [Server] Server thread/DEBUG #16 src/pocketmine/Player(3115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
19.04 01:58:31 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
19.04 01:58:31 [Server] Server thread/DEBUG #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 73.29.206.74 59896, raklib\protocol\EncapsulatedPacket object, integer 0)
19.04 01:58:31 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
19.04 01:58:31 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
19.04 01:58:31 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
19.04 01:58:31 [Server] Server thread/DEBUG #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
19.04 01:58:31 [Server] Server thread/DEBUG #23 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1555639111.9847)
19.04 01:58:31 [Server] Server thread/DEBUG #24 src/pocketmine/Server(2196): pocketmine\Server->tickProcessor()
19.04 01:58:31 [Server] Server thread/DEBUG #25 src/pocketmine/Server(1775): pocketmine\Server->start()
19.04 01:58:31 [Server] Server thread/DEBUG #26 src/pocketmine/PocketMine(258): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.04 01:58:31 [Server] Server thread/DEBUG #27 (1): require(string phar:///PMMP-1.10.0-Latest-Stable.phar/src/pocketmine/PocketMine.php)
19.04 01:58:31 [Server] Server thread/INFO mikeygio10[/73.29.206.74:59896] logged out due to Internal server error
19.04 01:58:31 [Server] RakLibServer thread/NOTICE Blocked 73.29.206.74 for 5 seconds
19.04 01:58:45 [Server] Server thread/CRITICAL Error: "Call to a member function setLastPos() on null" (EXCEPTION) in "plugins/PMEssentials_dev-46.phar/src/pmessentials/PMEssentials/listener/BackListener" at line 17
19.04 01:58:45 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): pmessentials\PMEssentials\listener\BackListener->onTeleport(pocketmine\event\entity\EntityTeleportEvent object)
19.04 01:58:45 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(pmessentials\PMEssentials\listener\BackListener object, pocketmine\event\entity\EntityTeleportEvent object)
19.04 01:58:45 [Server] Server thread/DEBUG #2 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\entity\EntityTeleportEvent object)
19.04 01:58:45 [Server] Server thread/DEBUG #3 src/pocketmine/entity/Entity(1948): pocketmine\event\Event->call()
19.04 01:58:45 [Server] Server thread/DEBUG #4 src/pocketmine/Player(3755): pocketmine\entity\Entity->teleport(pocketmine\level\Position object, NULL , NULL )
19.04 01:58:45 [Server] Server thread/DEBUG #5 plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader(16): pocketmine\Player->teleport(pocketmine\level\Position object)
19.04 01:58:45 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/MethodEventExecutor(38): philipshilling\alwaysspawn\Loader->onPlayerLogin(pocketmine\event\player\PlayerLoginEvent object)
19.04 01:58:45 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(philipshilling\alwaysspawn\Loader object, pocketmine\event\player\PlayerLoginEvent object)
19.04 01:58:45 [Server] Server thread/DEBUG #8 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerLoginEvent object)
19.04 01:58:45 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2108): pocketmine\event\Event->call()
19.04 01:58:45 [Server] Server thread/DEBUG #10 src/pocketmine/Player(2091): pocketmine\Player->completeLoginSequence()
19.04 01:58:45 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(125): pocketmine\Player->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
19.04 01:58:45 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(62): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
19.04 01:58:45 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
19.04 01:58:45 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
19.04 01:58:45 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
19.04 01:58:45 [Server] Server thread/DEBUG #16 src/pocketmine/Player(3115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
19.04 01:58:45 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
19.04 01:58:45 [Server] Server thread/DEBUG #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 73.29.206.74 59896, raklib\protocol\EncapsulatedPacket object, integer 0)
19.04 01:58:45 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
19.04 01:58:45 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
19.04 01:58:45 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
19.04 01:58:45 [Server] Server thread/DEBUG #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
19.04 01:58:45 [Server] Server thread/DEBUG #23 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1555639125.4347)
19.04 01:58:45 [Server] Server thread/DEBUG #24 src/pocketmine/Server(2196): pocketmine\Server->tickProcessor()
19.04 01:58:45 [Server] Server thread/DEBUG #25 src/pocketmine/Server(1775): pocketmine\Server->start()
19.04 01:58:45 [Server] Server thread/DEBUG #26 src/pocketmine/PocketMine(258): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.04 01:58:45 [Server] Server thread/DEBUG #27 (1): require(string phar:///PMMP-1.10.0-Latest-Stable.phar/src/pocketmine/PocketMine.php)

**Comment by AndreasHGK** [comment]
This should now be fixed
