### ISSUE TITLE
[REQUEST] Vanish Improvement by adding /interaction

### ISSUE THREAD

**Issue by dearminder** [pmessentials/PMEssentials#24]
Hi, I just got a idea for you to add a additional command. When Someone is on vanish then he is automaticaly ignored from interactions like placing dropping etc. and then you can use new interaction command (/it or /interaction)

**Comment by AndreasHGK** [comment]
That would be... spectator mode?

**Comment by dearminder** [comment]
Kinda but you cant pass trought walls

**Comment by AndreasHGK** [comment]
That’s not very useful though. I dont know why you would need this and I don’t think I will add this.

**Comment by dearminder** [comment]
It is. Vanish should make yourself fully invisible, If you accidentaly place block or break then it breaks everything but with this additional feature it would be easier to be hidden

**Comment by AndreasHGK** [comment]
So it's spectator.

**Comment by dearminder** [comment]
Only parts of it like no accidentaly grief, collecting dropped items and without noclip But ok
