### ISSUE TITLE
[BUG] Size not working + Fix

### ISSUE THREAD

**Issue by dearminder** [pmessentials/PMEssentials#25]
**Describe the bug**
/size shows error

**To Reproduce**
1. Use Size command
**Versions:**
 - Any

**Fix:**
Change in **PlayerSizeChangeEvent.php**

 `public function __construct(Player $player, CommandSender $sender, float $size)`

to
`public function __construct($player, $sender, $size)`

**Comment by AndreasHGK** [comment]
Whats the error?

**Comment by dearminder** [comment]
Internal server error, i dont remember but im already making a pull request with this fixed also

**Comment by AndreasHGK** [comment]
Dont just remove the types. Theres probably something else u can do

**Comment by dearminder** [comment]
Error 0: Argument 3 passed to pmessentials\PMEssentials\event\PlayerSizeChangeEvent::__construct() must be of the type float, string given, called in /storage/emulated/0/PocketMine-MP/plugins/PMEssentials-master/src/pmessentials/PMEssentials/command/SizeCommand.php on line 55 on line 16 in file /storage/emulated/0/PocketMine-MP/plugins/PMEssentials-master/src/pmessentials/PMEssentials/event/PlayerSizeChangeEvent.php
This is what it says

**Comment by AndreasHGK** [comment]
Alright i’ll fix that

**Comment by AndreasHGK** [comment]
Should be fixed
