### ISSUE TITLE
[BUG] Plugin crashes after /reload

### ISSUE THREAD

**Issue by dearminder** [pmessentials/PMEssentials#26]
**Describe the bug**
Plugin shutdown after /reload

**To Reproduce**
1. /reload

**Versions:**
 - Pocketmine version: 3.8.2
 - Plugin version: 1.0,0-dev (latest)
 - Minecraft version: doesnt matter

**Error:**
[Server thread/CRITICAL]: pocketmine\plugin\PluginException: "Plugin attempted to register pmessentials\PMEssentials\listener\VanishListener while not enabled" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 721

**Comment by AndreasHGK** [comment]
It’s probably best if you don’t reload. There are a ton of plugins that have problems reloading. It’s just not usable right now
