### ISSUE TITLE
[BUG] Messed Permission + FIX

### ISSUE THREAD

**Issue by dearminder** [pmessentials/PMEssentials#27]
**Describe the bug**
Typos in Permissions:
- in `PowertoolListener.php` , `powertools.use`
should be changed to `powertool.use`
- in GodCommand.php `god.self` and `god.other` should be changd to `godmode.self` and `godmode.other`
- in GameModeCommand.php should be changed  `$gmstr = self::toString($gm);` to `$gmstr = lcfirst(self::toString($gm));` And in responses `$gmstr` should be changed to `ucfirst($gmstr)`

**Comment by AndreasHGK** [comment]
If you think this’ll fix it, you can always make a pull request. I won’t have time to upgrade the plugin for a while. Thank you.
