### ISSUE TITLE
PMEssentials Disabled

### ISSUE THREAD

**Issue by archerunlimited** [pmessentials/PMEssentials#30]
When loading server, this appears when loading PMEssentials:
`18.06 17:49:12 [Server] Server thread/CRITICAL pocketmine\plugin\PluginException: "Plugin attempted to register pmessentials\PMEssentials\listener\VanishListener while not enabled" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 721`

**Comment by AndreasHGK** [comment]
i'm not supporting reloading
